FROM registry-vpc.cn-beijing.aliyuncs.com/yuuyoo/openjdk:1.8
MAINTAINER dave@yuuyoo.com

COPY account-0.0.1-SNAPSHOT.jar /deployments/app.jar

ENV URL="http://127.0.0.1:8014/manage/status"
EXPOSE 8013 8014
